plugins {
    alias libs.plugins.loom
    alias libs.plugins.mod.publish
}

base {
    archivesName = project.archives_base_name
}
version = "${project.version}+mc${libs.versions.minecraft.get()}"
group = project.maven_group

repositories {
    maven {
        name 'xanderRepoReleases'
        url 'https://maven.isxander.dev/releases'
    }
    maven {
        name 'Terraformers'
        url 'https://maven.terraformersmc.com'
    }
}

dependencies {
    minecraft libs.minecraft
    implementation libs.loader

    implementation libs.yacl
    implementation libs.modmenu
}

processResources {
    inputs.property 'version', version

    filesMatching('fabric.mod.json') {
        expand 'version': version
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25

    withSourcesJar()
}

jar {
    from('LICENSE') {
        rename { "${it}_${base.archivesName.get()}" }
    }
}

publishMods {
    file = jar.archiveFile
    changelog = file("changelogs/${project.version}.md").text
    type = STABLE
    modLoaders.add("fabric")

    modrinth {
        projectId = "S1v2ASLQ"
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        minecraftVersions.addAll("26.1", "26.1.1", "26.1.2") // better way to do this?
        requires("yacl")
    }

    curseforge {
        projectId = "1369273"
        projectSlug = "freelook-oneconfig"
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        minecraftVersions.addAll("26.1", "26.1.1", "26.1.2")
        requires("yacl")
    }

    discord {
        webhookUrl = providers.environmentVariable("DISCORD_WEBHOOK")
    }
}