[versions]
loader = "0.19.2"
minecraft = "1.21.10"

yacl = "3.8.2+1.21.10-fabric"
modmenu = "16.0.1"

loom = "1.16-SNAPSHOT"
mod-publish = "1.1.0"

[libraries]
loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

yacl = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[plugins]
loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "loom" }
mod-publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }